#!/usr/bin/env python3
"""Generate src/FontsFree.cpp from vendor/fonts/inter/*.ttf."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
files = [
    ("UI_FONT_REGULAR", root / "vendor" / "fonts" / "inter" / "Inter-Medium.ttf"),
    ("UI_FONT_BOLD", root / "vendor" / "fonts" / "inter" / "Inter-Black.ttf"),
]
out_cpp = root / "src" / "FontsFree.cpp"


def emit_array(name: str, data: bytes) -> str:
    lines = [f"const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const size_t {name}_SIZE = sizeof({name});")
    lines.append("")
    return "\n".join(lines)


parts = [
    '#include "Fonts.h"\n\n',
    "// Generated by tools/gen_fonts.py — do not edit.\n\n",
]
for name, path in files:
    data = path.read_bytes()
    parts.append(emit_array(name, data))
    print(f"{name}: {len(data)} bytes from {path.name}")

out_cpp.write_text("".join(parts), encoding="utf-8", newline="\n")
print(f"wrote {out_cpp} ({out_cpp.stat().st_size} bytes)")
